version: 2
updates:
  - package-ecosystem: "cargo"
    schedule:
      interval: "daily"
    reviewers:
      - "RealHinome"
    assignees:
      - "RealHinome"
    # Disable all updates except security updates
    open-pull-requests-limit: 0
