version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "vitest"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"
