max_width = 80
indent_style = "Block"
match_block_trailing_comma = true
binop_separator = "Back"
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
