# Define port for the HTTP API
port: 1111

# Remini server URL.
remini_url: ~

database:
  scylla:
    username: cassandra
    password: cassandra
    hosts:
      - 127.0.0.1:9042
  memcached:
    hosts:
      - 127.0.0.1:11211
  nats:
    publish: true
    host: 127.0.0.1:11211

services: # List of Gravitalia's connected services
  - http://gravitalia:8888
