# Define port for the HTTP API.
port: 1111

# Remini server URL.
remini_url: http://remini:50051
# Telemetry
prometheus: true
jaeger_url: http://jaeger:4317

database:
  scylla:
    username: cassandra
    password: cassandra
    hosts:
      - scylla:9042
    pool_size: 10
  memcached:
    hosts:
      - memcached:11211
    pool_size: 10
  kafka:
    hosts:
      - kafka:9092
    pool_size: 3

image_delivery:
  platform: Cloudinary # Only support Cloudinary.
  cloud_name: aaaaa1234
  key: "111111111111111"
  secret: SECRET
