name: Autha
url: https://auth.gravitalia.com
favicon: https://account.gravitalia.com/favicon.webp
terms_of_service: https://policies.gravitalia.com/terms
privacy_policy: https://policies.gravitalia.com/privacy
invite_only: false

postgres:
  address: postgres:5432
  database: autha
  username: postgres
  password: postgres
  ssl: false

ldap:
  address: ldap://openldap:389
  user: CN=admin,DC=domain,DC=local
  password: admin
  base_dn: DC=domain,DC=local
  additional_users_dn: OU=users
  users_filter: (&(uid={user_id}))
  additional_groups_dn: OU=groups
  groups_filter: (&(member={dn})(objectClass=groupOfNames))

totp:
  issuer: autha
  algorithm: sha1
  digits: 6
  period: 30 # in seconds

# Only support ES256.
token:
  key_id: j3Xz32VQ1S
  private_key_pem: |-
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgg8wQwttCoiBA9yQZ
    Uo+lImtpakc48rw9mHTPhD6k5A+hRANCAATkZYzb0mgzeeckNkE2dKlwX9zxW9Qz
    4JtlLQH76IOhXNObDGrsrsEeo5KDCQe1rrkYT/mTNuWepEEotRd4DRvf
    -----END PRIVATE KEY-----
  public_key_pem: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5GWM29JoM3nnJDZBNnSpcF/c8VvU
    M+CbZS0B++iDoVzTmwxq7K7BHqOSgwkHta65GE/5kzblnqRBKLUXeA0b3w==
    -----END PUBLIC KEY-----