name: Autha
url: https://auth.gravitalia.com
favicon: https://account.gravitalia.com/favicon.webp
terms_of_service: https://policies.gravitalia.com/terms
privacy_policy: https://policies.gravitalia.com/privacy
invite_only: false

postgres:
  address: postgres:5432
  database: autha
  username: postgres
  password: postgres
  ssl: false

ldap:
  address: ldap://openldap:389
  user: CN=admin,DC=domain,DC=local
  password: admin
  base_dn: DC=domain,DC=local
  additional_users_dn: OU=users
  users_filter: (&(uid={user_id}))
  additional_groups_dn: OU=groups
  groups_filter: (&(member={dn})(objectClass=groupOfNames))

totp:
  issuer: autha
  algorithm: sha1
  digits: 6
  period: 30 # in seconds

token:
  private_key_pem: |-
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDCMClJpwGVWFGanuWX/
    ezIV1getxkwBJTcqClVE1H6UqoCtag16Hsyt1cjjb1vhydmhZANiAARYdoKAVXgO
    MV6cKPdzPo9sS3UaiiPBJydddOQvQ43oFCD9eyg759qDJzOkH2ZNRPM3x7XDk1be
    taQW6eDAAavXBW7WZyxYt4DlSkmbyklbNv7IoQ4ABvG2FBJice1yEKQ=
    -----END PRIVATE KEY-----
  public_key_pem: |-
    -----BEGIN PUBLIC KEY-----
    MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEWHaCgFV4DjFenCj3cz6PbEt1GoojwScn
    XXTkL0ON6BQg/XsoO+fagyczpB9mTUTzN8e1w5NW3rWkFungwAGr1wVu1mcsWLeA
    5UpJm8pJWzb+yKEOAAbxthQSYnHtchCk
    -----END PUBLIC KEY-----