name: Autha
url: https://auth.gravitalia.com
favicon: https://account.gravitalia.com/favicon.webp
terms_of_service: https://account.gravitalia.com/terms.pdf
privacy_policy: https://account.gravitalia.com/privacy.pdf
invite_only: false

# Database.
postgres:
  address: postgres:5432
  database: autha
  username: postgres
  password: postgres
  pool_size: 25
  ssl: false

# Password hasher.
argon2:
  memory_cost: 65536 # 64 MiB.
  iterations: 4
  parallelism: 2
  hash_length: 32

# Enterprise-grade annuary.
ldap:
  address: ldap://openldap:389
  user: CN=admin,DC=domain,DC=local
  password: admin
  base_dn: DC=domain,DC=local
  additional_users_dn: OU=users
  users_filter: (&(uid={user_id}))
  additional_groups_dn: OU=groups
  groups_filter: (&(member={dn})(objectClass=groupOfNames))

# Multi-factor authentification (one time code).
totp:
  issuer: autha
  algorithm: sha1
  digits: 6
  period: 30 # in seconds

# JWT manager.
# You MUST use ES256 to generate key pair.
token:
  key_id: j3Xz32VQ1S
  private_key_pem: |-
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgg8wQwttCoiBA9yQZ
    Uo+lImtpakc48rw9mHTPhD6k5A+hRANCAATkZYzb0mgzeeckNkE2dKlwX9zxW9Qz
    4JtlLQH76IOhXNObDGrsrsEeo5KDCQe1rrkYT/mTNuWepEEotRd4DRvf
    -----END PRIVATE KEY-----
  public_key_pem: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5GWM29JoM3nnJDZBNnSpcF/c8VvU
    M+CbZS0B++iDoVzTmwxq7K7BHqOSgwkHta65GE/5kzblnqRBKLUXeA0b3w==
    -----END PUBLIC KEY-----