# Define port for the HTTP API.
port: 1111

# Remini server URL.
remini_url: http://remini:50051
# Telemetry
prometheus: true
jaeger_url: http://jaeger:4317

database:
  scylla:
    username: cassandra
    password: cassandra
    hosts:
      - cassandra:9042
    pool_size: 10
  memcached:
    hosts:
      - memcached:11211
    pool_size: 10
  rabbitmq:
    hosts:
      - amqp://rabbitmq:5672/%2f
    pool_size: 5

services: # List of Gravitalia's connected services.
  - http://gravitalia:8888
