version: '3.9'

services:
  autha:
    image: ghcr.io/gravitalia/autha:3.0.0
    platform: linux/amd64
    container_name: autha
    restart: always
    environment:
      - CHACHA20_KEY=4D6A514749614D6C74595A50756956446E5673424142524C4F4451736C515233
      - AES256_KEY=4D6A514749614D6C74595A50756956446E5673424142524C4F4451736C515233
      - KEY=SECRET
      - MEMORY_COST=1048576
      - ROUND=2
      - HASH_LENGTH=32
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 1111:1111
    depends_on:
      cassandra:
        condition: service_started
      memcached:
        condition: service_started
    volumes:
      - ./config.yaml:/config.yaml

  cassandra:
    image: cassandra:latest
    restart: always
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    deploy:
      resources:
        limits:
          memory: 5g
        reservations:
          memory: 1g
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --execute='SELECT * FROM system_schema.keyspaces;' || exit 1"]
      interval: 10s
      start_period: 90s
      timeout: 10s
      retries: 5

  memcached:
    image: memcached:latest
    container_name: memcached
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 11211:11211

  rabbitmq:
    image: rabbitmq:3.12.11-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ./data/rabbitmq/data/:/var/lib/rabbitmq/
        - ./data/rabbitmq/log/:/var/log/rabbitmq
