services:
  autha:
    image: ghcr.io/gravitalia/autha
    platform: linux/amd64
    container_name: autha
    restart: always
    depends_on:
      - postgres
      - otel-collector
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/autha
      - OTEL_URL=http://otel:4317
    volumes:
      - ../status.json:/status.json
      
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autha
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - jaeger
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/conf:/etc/grafana/provisioning/datasources

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prometheus:/prometheus

  loki:
    container_name: loki
    image: grafana/loki:3.4
    depends_on:
      - promtail
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  otel-collector:
    container_name: otel
    image: otel/opentelemetry-collector:0.119.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - loki
      - prometheus