services:
  autha:
    image: ghcr.io/gravitalia/autha
    platform: linux/amd64
    container_name: autha
    restart: always
    depends_on:
      - postgres
      - otel-collector
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/autha
      - OTEL_URL=http://otel:4317
      - LDAP_URL=
    volumes:
      - ../status.json:/status.json
    networks:
      - authentification

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autha
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - authentification

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - 389:389
    environment:
      - LDAP_ROOT=dc=domain,dc=local
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_EXTRA_SCHEMAS=argon2
    volumes:
      - openldap-data:/bitnami/openldap
      - ./argon2.ldif:/opt/bitnami/openldap/etc/schema/argon2.ldif
    networks:
      - authentification

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - jaeger
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./data/grafana/conf:/etc/grafana/provisioning/datasources
    networks:
      - authentification

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    networks:
      - authentification

  loki:
    image: grafana/loki:3.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - promtail
    ports:
      - 3100:3100
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - authentification

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /var/log:/var/log
      - ./promtail.yaml:/etc/promtail/config.yaml
    networks:
      - authentification

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - authentification

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel
    restart: always
    command: --config=/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
      - loki
      - prometheus
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    volumes:
      - ./otel.yaml:/etc/otel-collector-config.yaml
    networks:
      - authentification

volumes:
  postgres-data:
  openldap-data:
  grafana-data:
  prometheus-data:
  loki-data:

networks:
  authentification:
    driver: bridge
