# Define port for the HTTP API.
port: 1111

# Machine learning to detect the presence of nudity in avatars.
# You can remove this line if you do not want to verify.
remini_url: http://remini:50051

database:
  scylla:
    username: cassandra
    password: cassandra
    hosts:
      - scylla:9042
    pool_size: 10
  memcached:
    hosts:
      - memcached:11211
    pool_size: 10
  kafka:
    hosts:
      - kafka:9092
    pool_size: 3

image_delivery:
  platform: Cloudinary # Only support Cloudinary.
  cloud_name: aaaaa1234
  key: "111111111111111"
  secret: SECRET

telemetry:
  prometheus: true # Deploys `/metrics` route containing metrics for Prometheus (cpu, ram, number of requests, status, time, etc.).
  jaeger: http://jaeger:6831 # Tracing using Jaeger port for thrift-compact protocol.
  loki: http://loki:3100 # Logging using Grafana Loki port for HTTP communications.
