version: '3.9'

services:
  autha:
    image: ghcr.io/gravitalia/autha:3.0.0
    platform: linux/amd64
    container_name: autha
    restart: always
    environment:
      - CHACHA20_KEY=4D6A514749614D6C74595A50756956446E5673424142524C4F4451736C515233
      - AES256_KEY=4D6A514749614D6C74595A50756956446E5673424142524C4F4451736C515233
      - KEY=SECRET
      - MEMORY_COST=1048576
      - ROUND=2
      - HASH_LENGTH=32
    ports:
      - 1111:1111
    depends_on:
      - cassandra
      - memcached
      - kafka
      - prometheus
      - jaeger
    volumes:
      - ./config.yaml:/config.yaml

  # Database
  cassandra:
    image: cassandra:latest
    restart: always
    container_name: cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    deploy:
      resources:
        limits:
          memory: 5g
        reservations:
          memory: 1g
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh --execute='SELECT * FROM system_schema.keyspaces;' || exit 1"]
      interval: 10s
      start_period: 90s
      timeout: 10s
      retries: 5

  memcached:
    image: memcached:alpine
    container_name: memcached
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 11211:11211

  # Message broker
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
  
  # Telemetry
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 6831:6831
      - 4317:4317
    environment:
      - LOG_LEVEL=info
