[book]
authors = ["Gravitalia", "RealHinome"]
language = "en"
multilingual = false
src = "src"
title = "Autha"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/Gravitalia/autha/tree/master/docs"
edit-url-template = "https://github.com/Gravitalia/autha/tree/master/docs/{path}"