[package]
name = "image_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
fast_image_resize = "2.7"
kamadak-exif = "0.5.5"
webp = "0.2.6"

cloudinary = "0.4.0"

anyhow = "1"
log = "0.4"