[workspace]
resolver = "2"
members = [
    "autha",
    "autha-limits",
    "crypto",
    "db",
    "image_processor",
]

[workspace.package]
version = "3.0.0"
description = "fast and safe authorization delegation and account management API"
homepage = "https://account.gravitalia.com"
readme = "README.md"
edition = "2021"
license = "MPL"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.dev]
opt-level = "z"
debug = true

[profile.dev.package.crypto]
opt-level = 3

[profile.bench.package.crypto]
opt-level = 3

[profile.release.package.image_processor]
opt-level = "z"

[workspace.dependencies]
warp = { version = "0.3", default-features = false }
