name: Autha/bazel

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  bazel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: ubuntu-latest
          name: Linux Ubuntu
    name: Build (${{ matrix.name || matrix.target }})
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-bazel
    - name: Update lockfile
      if: ${{ github.actor == 'dependabot[bot]' }}
      run: CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index
      shell: bash
    - name: Save lockfile
      uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ github.actor == 'dependabot[bot]' && matrix.target == 'ubuntu-latest' }}
      with:
        commit_message: 'chore(deps): Update Bazel lockfile'
    - name: Run builds
      run: bazel build //... -c opt
      shell: bash
    - name: Run tests
      run: bazel test //... -c opt
      shell: bash
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to docker.io
      if: ${{ github.ref == 'refs/heads/master' }}
      run: bazel run //autha:push -c opt
      shell: bash
