name: Publish Docker image

on:
  push:
    branches: [master]
    
env:
  REGISTRY: ghcr.io

jobs:
  push_autha:
    name: Publish Autha
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: "Get tag"
      id: "get-tag"
      shell: "bash"
      run: |
        echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT
        
    - name: Build the Docker image
      run: |
            docker build . --tag ghcr.io/gravitalia/autha:latest
            docker push ghcr.io/gravitalia/autha:latest
            docker tag ghcr.io/gravitalia/autha:latest ghcr.io/gravitalia/autha:${{ steps.get-tag.outputs.PKG_VERSION }}
            docker push ghcr.io/gravitalia/autha:${{ steps.get-tag.outputs.PKG_VERSION }}
